# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Device Discovery
version: "0.1"
slug: discover_devices
description: Discover devices on your network v2
url: "https://github.com/chanw28/home-assistant/tree/main/discover_devices"
arch:
  - amd64
#host_network: true
ports:
  8000/tcp: 8000
init: false
startup: application
boot: auto
options:
  apikey: "API key specifically for your login. Not in use at the moment"
schema:
  apikey: "str?"
#image: "ghcr.io/chanw28/home-assistant/{arch}-addon-discover_devices"
